//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Játékosok_adatai
    {
        public string USERNAME { get; set; }
        public string TELJES_NÉV { get; set; }
        public System.DateTime SZÜLETÉSI_DÁTUM { get; set; }
        public string LAKCÍM { get; set; }
        public string TELEFONSZÁM { get; set; }
    }
}
